const DISHES = [
  {
    id: "ayala_fry",
    emoji: "🐟",
    label: "Ayala Fry",
    title: "Ayala Fry",
    subtitle: "Kerala Mackerel Fish Fry",
    category: "Seafood · Fish Fry",
    tagline: "The crispy, spice-coated pride of the Kerala coast.",
    desc: "Kerala's beloved mackerel, marinated in a bold blend of red chilli, turmeric, ginger-garlic paste, and a splash of raw mango pulp, then shallow-fried in coconut oil until the edges crisp and caramelise. Ayala is the workhorse of Kerala coastal kitchens — affordable, intensely flavoured, and ready in minutes.",
    history: "Mackerel has been hauled ashore in Kerala's fishing villages for centuries. Eaten the same morning it's caught, it was the everyday protein of coastal communities long before refrigeration. The spice marinade evolved to balance the fish's natural oiliness — turmeric and chilli doing double duty as flavouring and preservative.",
    ingredients: "Mackerel, red chilli powder, turmeric, ginger-garlic paste, raw mango pulp, coconut oil, curry leaves, salt",
    difficulty: "Easy",
    time: "30 min",
    color: "#e05a30",
    glow: "#e05a30",
    r: 50
  },
  {
    id: "bbq_chicken",
    emoji: "🍗",
    label: "BBQ Chicken",
    title: "BBQ Chicken",
    subtitle: "Smoky Grilled Chicken",
    category: "Chicken · Grill",
    tagline: "Charred edges, smoky interior, sticky glaze.",
    desc: "Chicken marinated overnight in a blend of spices, yogurt, and a smoky BBQ glaze, then grilled at high heat until the skin blisters and chars at the edges. The inside stays tender and juicy while the outside develops a deep caramelised crust.",
    history: "BBQ chicken found its way into Kerala homes through the influence of Gulf returnees and the explosion of grilled food culture in the 1990s. Today it sits comfortably alongside nadan (traditional) dishes on every party spread.",
    ingredients: "Chicken, yogurt, BBQ sauce, garlic, ginger, cumin, paprika, lemon juice, oil",
    difficulty: "Medium",
    time: "1 hr + marinate",
    color: "#8b3a2a",
    glow: "#8b3a2a",
    r: 52
  },
  {
    id: "chatti_choru",
    emoji: "🍚",
    label: "Chatti Choru",
    title: "Chatti Choru",
    subtitle: "Clay Pot Rice",
    category: "Rice · Kerala Classic",
    tagline: "Rice with an earthen soul.",
    desc: "Kerala red rice slow-cooked in an unglazed clay pot (chatti), served with an array of traditional accompaniments — fish fry, thoran, pickles, and papadum. The clay vessel imparts a subtle mineral warmth and a faint smokiness that no steel pot can replicate.",
    history: "Chatti Choru is as old as Kerala's clay pottery tradition. Before aluminium vessels reached village kitchens, every household cooked in earthen pots. The chatti seals in moisture and infuses the rice with the unique taste of the earth — something modern cookware has never been able to match.",
    ingredients: "Kerala matta rice, water, salt — accompaniments: fish fry, thoran, pickle, papadum",
    difficulty: "Easy",
    time: "45 min",
    color: "#9b7a50",
    glow: "#9b7a50",
    r: 54
  },
  {
    id: "chilli_chicken",
    emoji: "🌶️",
    label: "Chilli Chicken",
    title: "Chilli Chicken",
    subtitle: "Indo-Chinese Classic",
    category: "Chicken · Indo-Chinese",
    tagline: "Crispy, saucy, fiery — the canteen favourite.",
    desc: "Crispy-fried chicken pieces tossed at high heat with green chillis, spring onions, soy sauce, and vinegar until glossy and crackling. It's bold, tangy, and unapologetically addictive — one of those dishes that disappears off the plate before it even hits the table.",
    history: "Chilli chicken was born in the Chinese restaurants of Kolkata in the 1970s and spread across India like wildfire. Kerala adapted it with extra heat and a slightly tangier balance — suiting the local palate perfectly.",
    ingredients: "Chicken, green chilli, spring onion, soy sauce, vinegar, cornflour, garlic, ginger, bell pepper, oil",
    difficulty: "Medium",
    time: "40 min",
    color: "#c93030",
    glow: "#c93030",
    r: 50
  },
  {
    id: "cutlets",
    emoji: "🥙",
    label: "Cutlets",
    title: "Kerala Cutlets",
    subtitle: "Spiced Meat Patties",
    category: "Snack · Deep Fry",
    tagline: "Golden, crunchy, and impossible to eat just one.",
    desc: "Spiced minced meat — usually beef or chicken — mixed with mashed potato, onion, and aromatics, shaped into patties, dipped in beaten egg, coated in breadcrumbs, and pan-fried golden. A staple at every Kerala tea party, wedding, and Christmas feast.",
    history: "Cutlets came to Kerala kitchens via the colonial influence of the Portuguese and British. Kerala's Syrian Christian community embraced and evolved the form, adding their signature spice profile — making it distinctly Malayali.",
    ingredients: "Minced meat, potato, onion, green chilli, ginger, garlic, garam masala, egg, breadcrumbs, oil",
    difficulty: "Medium",
    time: "1 hr",
    color: "#c4883a",
    glow: "#c4883a",
    r: 48
  },
  {
    id: "egg_roast",
    emoji: "🍳",
    label: "Egg Roast",
    title: "Kerala Egg Roast",
    subtitle: "Mutta Roast — Breakfast's Best Companion",
    category: "Eggs · Breakfast",
    tagline: "The most important egg dish in Kerala.",
    desc: "Hard-boiled eggs fried and then simmered in a deeply caramelised onion and tomato masala, spiced with red chilli, coriander, and garam masala, finished with a glug of coconut oil. Served with idiyappam, pathiri, or appam — this is the dish that makes Kerala breakfasts legendary.",
    history: "Egg roast is believed to have emerged in the homes of Kerala's Christian and Muslim communities, where it became a staple breakfast accompaniment. It travels well, keeps without refrigeration for hours, and only gets better as it absorbs the masala.",
    ingredients: "Eggs, onion, tomato, red chilli, coriander powder, garam masala, coconut oil, curry leaves, ginger-garlic paste",
    difficulty: "Easy",
    time: "35 min",
    color: "#d4600c",
    glow: "#d4600c",
    r: 56
  },
  {
    id: "egg_stew",
    emoji: "🥚",
    label: "Egg Stew",
    title: "Kerala Egg Stew",
    subtitle: "Coconut Milk Egg Curry",
    category: "Eggs · Stew",
    tagline: "Gentle heat, creamy coconut, quiet spices.",
    desc: "Eggs simmered in a fragrant coconut milk gravy seasoned with whole peppercorns, green chilli, ginger, and curry leaves. Unlike the bold and spicy egg roast, the stew is mild, silky, and quietly complex. Best eaten with soft appam to soak up every drop of the gravy.",
    history: "Kerala stews (ishtu) are rooted in the Syrian Christian culinary tradition, where spicing is restrained and coconut milk does the heavy lifting. The stew was designed to complement the lacy appam — together they form one of Kerala's most iconic pairings.",
    ingredients: "Eggs, coconut milk, green chilli, ginger, peppercorns, curry leaves, shallots, coconut oil",
    difficulty: "Easy",
    time: "30 min",
    color: "#7a9a8a",
    glow: "#7a9a8a",
    r: 46
  },
  {
    id: "fish_curry",
    emoji: "🍲",
    label: "Fish Curry",
    title: "Kerala Fish Curry",
    subtitle: "Meen Curry — The Soul of Kerala",
    category: "Seafood · Curry",
    tagline: "Tangy, fiery, and unmistakably home.",
    desc: "A punchy, blood-red curry made with kudampuli (Malabar tamarind or fish tamarind), fresh coconut paste, and a robust spice base. The kudampuli gives it a sour depth unlike any other acid in cooking. Made in a clay pot, this curry tastes better the next day — and even better the day after that.",
    history: "Kerala fish curry is as old as the state itself. The kudampuli was used by fishermen to preserve fish and create a portable, flavourful curry they could carry at sea. Every village, every household has their own version — this is ours.",
    ingredients: "Fish, kudampuli, coconut paste, red chilli, shallots, ginger, garlic, turmeric, curry leaves, coconut oil",
    difficulty: "Medium",
    time: "45 min",
    color: "#c02020",
    glow: "#c02020",
    r: 60
  },
  {
    id: "ghee_rice",
    emoji: "✨",
    label: "Ghee Rice",
    title: "Ghee Rice",
    subtitle: "Ney Choru — Malabar's Festive Rice",
    category: "Rice · Malabar",
    tagline: "Every grain glistening, every bite fragrant.",
    desc: "Long-grain basmati cooked in clarified butter (ghee) with whole spices — cardamom, cloves, cinnamon — then garnished with deep-fried cashews, golden raisins, and crisp shallots. Served at weddings, Eid feasts, and any occasion that deserves celebration.",
    history: "Ghee rice is a cornerstone of Malabar cuisine, rooted in the spice trade era when Arab traders and their culinary traditions merged with Kerala's coastal cooking. It became the defining dish of Kerala Muslim feasts — inseparable from the biryani and korma that surround it.",
    ingredients: "Basmati rice, ghee, cardamom, cloves, cinnamon, bay leaf, shallots, cashews, raisins, rose water",
    difficulty: "Medium",
    time: "45 min",
    color: "#c8a830",
    glow: "#c8a830",
    r: 54
  },
  {
    id: "idiyappam_mutton_curry",
    emoji: "🍝",
    label: "Idiyappam",
    title: "Idiyappam & Mutton Curry",
    subtitle: "String Hoppers with Braised Mutton",
    category: "Breakfast · Combination",
    tagline: "Silk and spice on the same plate.",
    desc: "Freshly steamed rice noodle strings — light, airy, almost cloud-like — served alongside a slow-braised mutton curry where the meat has had hours to surrender its flavour into a dark, deeply spiced gravy. The delicate idiyappam soaks up the bold curry beautifully.",
    history: "Idiyappam is ancient — pressed from rice flour using a wooden or metal press called an aachu, it has been eaten across South India and Sri Lanka for generations. Paired with mutton curry, it became a weekend morning ritual in many Kerala homes.",
    ingredients: "Rice flour, water, salt — Mutton curry: mutton, coconut milk, onion, tomato, spices, curry leaves",
    difficulty: "Medium",
    time: "1.5 hrs",
    color: "#8a6040",
    glow: "#8a6040",
    r: 56
  },
  {
    id: "kadala_curry",
    emoji: "🫘",
    label: "Kadala Curry",
    title: "Kadala Curry",
    subtitle: "Black Chickpea Curry",
    category: "Vegetarian · Curry",
    tagline: "The puttu's essential soulmate.",
    desc: "Black chickpeas (kadala) slow-cooked with freshly roasted and ground coconut masala, shallots, and a warming spice blend. Earthy, slightly smoky, and robust — kadala curry is the dish that makes puttu a complete meal and Kerala's most beloved vegetarian pairing.",
    history: "Kadala curry has been part of the Kerala breakfast table for as long as puttu has existed. The black chickpea, imported from drier climates, became a reliable protein source for Kerala's largely coastal population — and the roasted coconut masala is a technique uniquely Keralite.",
    ingredients: "Black chickpeas, coconut, shallots, red chilli, coriander, garam masala, coconut oil, curry leaves",
    difficulty: "Medium",
    time: "1 hr",
    color: "#5a3a20",
    glow: "#5a3a20",
    r: 50
  },
  {
    id: "kanthari_chicken",
    emoji: "🌿",
    label: "Kanthari Chicken",
    title: "Kanthari Chicken",
    subtitle: "Bird's Eye Chilli Chicken",
    category: "Chicken · Spicy",
    tagline: "Small chilli. Big fire. Silky coconut.",
    desc: "Chicken cooked with kanthari — the tiny, ferociously hot bird's eye chilli native to Kerala — balanced with the creaminess of fresh coconut milk. The heat from kanthari is sharp and immediate, cutting through the richness of the gravy. Addictive for those who can handle it.",
    history: "Kanthari mullagu (bird's eye chilli) grows wild and in home gardens across Kerala, revered for its medicinal and culinary properties. It was traditionally used as much for health — anti-inflammatory, digestive — as it was for flavour. Kanthari chicken is the ultimate showcase of this tiny powerhouse.",
    ingredients: "Chicken, kanthari (bird's eye chilli), coconut milk, shallots, ginger, garlic, turmeric, coconut oil, curry leaves",
    difficulty: "Medium",
    time: "50 min",
    color: "#40a060",
    glow: "#40a060",
    r: 52
  },
  {
    id: "kerala_chicken_fry",
    emoji: "🍗",
    label: "Chicken Fry",
    title: "Kerala Chicken Fry",
    subtitle: "Nadan Kozhi Varuthathu",
    category: "Chicken · Fry",
    tagline: "Dark, aromatic, and worth every minute of marination.",
    desc: "Chicken pieces marinated deep in a paste of red chilli, black pepper, ginger, garlic, and coriander powder, then shallow-fried until the coating chars slightly at the edges and the inside stays moist. The dark spice crust is the whole point — intense, smoky, and robustly flavoured.",
    history: "Nadan (traditional) chicken fry is a staple of Kerala homes and road-side toddy shops (tapioca and chicken being a classic pairing). Each region has its own spice ratio, but the dark colour from chilli and slow frying is consistent across every version.",
    ingredients: "Chicken, red chilli powder, black pepper, ginger-garlic paste, coriander powder, turmeric, coconut oil, curry leaves",
    difficulty: "Easy",
    time: "1 hr",
    color: "#a05020",
    glow: "#a05020",
    r: 52
  },
  {
    id: "kozhukkattai",
    emoji: "🫔",
    label: "Kozhukkattai",
    title: "Kozhukkattai",
    subtitle: "Steamed Rice Flour Dumplings",
    category: "Sweet · Festive",
    tagline: "Banana leaf steam, coconut heart, jaggery soul.",
    desc: "Soft rice flour dumplings filled with a warm mixture of grated coconut and melted jaggery, shaped into little ovals and steamed until just set. The outer shell is silky-smooth and slightly translucent; the inside is fragrant and sweet. Made for festivals and eaten with quiet reverence.",
    history: "Kozhukkattai is closely associated with Vinayaka Chaturthi — it is Lord Ganesha's favourite offering in South Indian tradition. Across Tamil Nadu and Kerala, no Chaturthi celebration is complete without a plate of freshly made kozhukkattai.",
    ingredients: "Rice flour, grated coconut, jaggery, cardamom, water, pinch of salt",
    difficulty: "Medium",
    time: "1 hr",
    color: "#8a7ab8",
    glow: "#8a7ab8",
    r: 44
  },
  {
    id: "liver_fry",
    emoji: "🥩",
    label: "Liver Fry",
    title: "Liver Fry",
    subtitle: "Kalleera Varuthathu — Spicy Offal Fry",
    category: "Meat · Fry",
    tagline: "Bold, iron-rich, and deeply spiced.",
    desc: "Tender pieces of liver — usually beef or chicken — flash-fried with pearl onions, green chillis, and curry leaves in a dry, punchy masala. The liver is cooked just long enough to lose its rawness while keeping its silky interior. Served as a side with rice or as a snack with drinks.",
    history: "Liver fry is a staple of Kerala's non-vegetarian households, particularly during festival slaughters like Bakrid when the whole animal is cooked. It is prized for its nutritional density and its ability to take on bold spice with grace.",
    ingredients: "Liver, pearl onions, green chilli, ginger, garlic, turmeric, pepper, garam masala, curry leaves, coconut oil",
    difficulty: "Easy",
    time: "30 min",
    color: "#6a2820",
    glow: "#6a2820",
    r: 46
  },
  {
    id: "moloshum",
    emoji: "🥣",
    label: "Moloshyam",
    title: "Moloshyam",
    subtitle: "Kerala Pepper & Coconut Broth",
    category: "Vegetarian · Curry",
    tagline: "Thin, tangy, and quietly restorative.",
    desc: "A light, broth-like curry made with freshly ground coconut, black pepper, cumin, and tamarind. Moloshyam is deliberately simple — it is the dish you eat when you want to reset, when the body needs something clean and digestive. Often cooked with yam or raw plantain.",
    history: "Moloshyam is one of Kerala's oldest culinary forms — a pre-spice-trade curry that relies on pepper (native to Kerala) rather than imported chilli. It appears in traditional Ayurvedic cooking as a digestive and restorative dish.",
    ingredients: "Coconut, black pepper, cumin, tamarind, turmeric, yam or raw plantain, shallots, curry leaves",
    difficulty: "Easy",
    time: "30 min",
    color: "#a0a830",
    glow: "#a0a830",
    r: 42
  },
  {
    id: "mutton_stew",
    emoji: "🍖",
    label: "Mutton Stew",
    title: "Kerala Mutton Stew",
    subtitle: "Mutton Ishtu — Coconut Milk Braise",
    category: "Meat · Stew",
    tagline: "Low and slow, milk-white and full of warmth.",
    desc: "Bone-in mutton slow-cooked with potato, pearl onion, green chilli, and ginger in a milky coconut gravy. The spices are whole and restrained — cardamom, cloves, cinnamon — letting the coconut milk carry the flavour. Mild but deeply satisfying, best with lacy appam or idiyappam.",
    history: "The stew (ishtu) tradition in Kerala is rooted in the Syrian Christian community of central Kerala. It arrived as an adaptation of European braise techniques filtered through a local pantry — the result is something entirely unique to Kerala.",
    ingredients: "Mutton, potato, coconut milk, pearl onions, green chilli, ginger, cardamom, cloves, cinnamon, coconut oil",
    difficulty: "Medium",
    time: "1.5 hrs",
    color: "#9898b8",
    glow: "#9898b8",
    r: 56
  },
  {
    id: "neymeen_fry",
    emoji: "🐠",
    label: "Neymeen Fry",
    title: "Neymeen Fry",
    subtitle: "King Fish (Seer Fish) Fry",
    category: "Seafood · Fish Fry",
    tagline: "Royal fish, royal treatment.",
    desc: "Thick steaks of neymeen (king fish / seer fish) marinated in a vivid red paste of chilli, turmeric, black pepper, and raw mango or vinegar, then pan-fried in coconut oil until a crust forms that seals in the firm, meaty flesh. Neymeen is the prestige fish of Kerala — served at feasts and celebrations.",
    history: "Neymeen (seer fish or king fish) has always been considered a luxury catch along the Kerala coastline. Its firm, low-bone flesh made it ideal for frying — and the spice crust was developed to honour the fish's natural richness rather than overwhelm it.",
    ingredients: "King fish steaks, red chilli, turmeric, black pepper, ginger-garlic paste, raw mango or vinegar, coconut oil",
    difficulty: "Easy",
    time: "35 min",
    color: "#d47820",
    glow: "#d47820",
    r: 54
  },
  {
    id: "oratti",
    emoji: "🫓",
    label: "Oratti",
    title: "Oratti",
    subtitle: "Kerala Rice Roti",
    category: "Bread · Malabar",
    tagline: "Soft, thin, and made from the simplest ingredients.",
    desc: "Unleavened rice flour flatbreads cooked on a dry griddle until they puff slightly and develop faint char marks. Oratti is the bread of Kerala's northern Malabar region — tender, slightly chewy, and the ideal vehicle for fish curry, mutton stew, or chilli chicken.",
    history: "Oratti (also called orotti or rice roti) predates wheat breads in Kerala — rice flour was the natural choice in a paddy-rich land. It was the everyday bread of Malabar's working households before chappathi became widespread.",
    ingredients: "Rice flour, water, salt, coconut milk (optional)",
    difficulty: "Easy",
    time: "30 min",
    color: "#c8b090",
    glow: "#c8b090",
    r: 42
  },
  {
    id: "payar",
    emoji: "🫛",
    label: "Payar",
    title: "Payar Curry",
    subtitle: "Cowpea / Long Beans Curry",
    category: "Vegetarian · Curry",
    tagline: "Humble, wholesome, and deeply satisfying.",
    desc: "Long beans or cowpeas cooked in a simple gravy of coconut, shallots, and spices. Payar is straightforward and unpretentious — it is the everyday curry that anchors a Kerala lunch. No drama, no complexity, just good flavour and honest cooking.",
    history: "Payar has been cultivated in Kerala for generations. It grows in home gardens alongside tapioca and banana plants — easily available, nutritious, and adaptable. The payar thoran (dry stir-fry) and payar curry represent the most fundamental expressions of Kerala vegetarian cooking.",
    ingredients: "Long beans or cowpeas, coconut, shallots, green chilli, cumin, turmeric, curry leaves, coconut oil",
    difficulty: "Easy",
    time: "30 min",
    color: "#4a8a40",
    glow: "#4a8a40",
    r: 44
  },
  {
    id: "pazham_pori",
    emoji: "🍌",
    label: "Pazham Pori",
    title: "Pazham Pori",
    subtitle: "Kerala Banana Fritters",
    category: "Snack · Sweet",
    tagline: "Kerala's most beloved tea-time ritual.",
    desc: "Ripe nendran plantain slices coated in a thin batter of flour, turmeric, and a little sugar, then deep-fried until golden and crisp on the outside, soft and caramel-sweet within. Eaten hot, with a glass of black tea, preferably in the rain. There is no better snack in the world.",
    history: "Pazham pori is as Keralite as the coconut tree. The nendran plantain — thick, starchy, and intensely flavoured when ripe — is unique to Kerala and ideal for frying. Every tea shop from Thiruvananthapuram to Kasaragod sells them, and every family makes their own version.",
    ingredients: "Nendran plantain (ripe), all-purpose flour, turmeric, sugar, coconut oil or oil for frying",
    difficulty: "Easy",
    time: "20 min",
    color: "#d4a020",
    glow: "#d4a020",
    r: 50
  },
  {
    id: "pothichoru",
    emoji: "🍃",
    label: "Pothichoru",
    title: "Pothichoru",
    subtitle: "Banana Leaf Rice Packet",
    category: "Rice · Kerala Heritage",
    tagline: "Packed at night. Perfect by noon.",
    desc: "Kerala red rice, chammanthi (coconut chutney), thoran, a fried egg omelette, fish fry, and mango pickle — all layered together and bundled tightly in banana leaf. Pothichoru isn't just food; it's an institution. Packed the evening before and carried to work, school, or the paddy field, it tastes better the longer it sits — the banana leaf infuses the rice with a green, grassy perfume.",
    history: "Pothichoru is one of Kerala's oldest food traditions — a portable lunch that sustained farmers, labourers, and travellers before tiffin boxes existed. The banana leaf isn't just packaging; it's part of the flavour. Every Keralite carries a memory of eating pothichoru somewhere — on a bus, under a tree, by a river.",
    ingredients: "Kerala matta rice, coconut chammanthi, thoran, egg omelette, fish fry, mango pickle, banana leaf",
    difficulty: "Medium",
    time: "1 hr",
    color: "#4a7840",
    glow: "#4a7840",
    r: 60
  },
  {
    id: "prawn_thokku",
    emoji: "🦐",
    label: "Prawn Thokku",
    title: "Prawn Thokku",
    subtitle: "Dry Spiced Prawn Masala",
    category: "Seafood · Dry Curry",
    tagline: "Intense, sticky, and gone before you expect it.",
    desc: "Prawns cooked down with tomatoes, onions, red chilli, and a blend of spices until all the moisture evaporates and the masala clings to each prawn in a dark, sticky coat. Thokku means 'cooked down to almost dry' — and that reduction is where all the flavour concentrates.",
    history: "Prawn thokku belongs to the coastal pantry of both Kerala and Tamil Nadu. In Kerala, it was a way to preserve prawns before refrigeration — cooking them down in spice and acid extended their shelf life while intensifying their flavour. Today it's sought after for precisely that intensity.",
    ingredients: "Prawns, tomato, onion, red chilli, coriander, garam masala, tamarind or raw mango, coconut oil, curry leaves",
    difficulty: "Easy",
    time: "40 min",
    color: "#c04040",
    glow: "#c04040",
    r: 50
  },
  {
    id: "uzhunnu_vada",
    emoji: "🍩",
    label: "Uzhunnu Vada",
    title: "Uzhunnu Vada",
    subtitle: "Crispy Urad Dal Fritters",
    category: "Snack · Breakfast",
    tagline: "Shattering crust. Cloud-light interior.",
    desc: "Urad dal soaked overnight and ground to a fluffy, airy batter with shallots, peppercorns, green chilli, ginger, and curry leaves, then shaped into rings and deep-fried until they achieve a satisfying crunch. The contrast between the shatteringly crisp exterior and the soft, savoury inside is the whole point.",
    history: "Vada (or wada) has been part of South Indian temple offerings and street food for over a thousand years. In Kerala, uzhunnu vada is synonymous with the morning — served with coconut chutney and sambar, it is the standard opening act of a proper Kerala breakfast.",
    ingredients: "Urad dal, shallots, green chilli, black pepper, ginger, curry leaves, rice flour (optional), oil for frying",
    difficulty: "Medium",
    time: "30 min + soak",
    color: "#c89840",
    glow: "#c89840",
    r: 48
  },
  {
    id: "vella_pachadi",
    emoji: "🥛",
    label: "Vella Pachadi",
    title: "Vella Pachadi",
    subtitle: "Coconut Yoghurt Relish",
    category: "Vegetarian · Condiment",
    tagline: "Cool, creamy, and the peacemaker on the plate.",
    desc: "A refreshing relish of grated coconut, yoghurt, and a gentle tempering of mustard seeds and curry leaves. Vella pachadi is the cooling counterpoint on a Kerala sadya (feast) plate — it soothes the heat, cuts through richness, and cleanses the palate between courses.",
    history: "Pachadi is a cornerstone of the Kerala sadya, where every element on the banana leaf has a role to play. Vella (white) pachadi is the mildest of the pachadis — no beetroot, no pineapple — just coconut and yoghurt doing their quiet work.",
    ingredients: "Grated coconut, yoghurt, green chilli, cumin, mustard seeds, curry leaves, coconut oil",
    difficulty: "Easy",
    time: "15 min",
    color: "#a0c0b0",
    glow: "#a0c0b0",
    r: 42
  }
];
